spring.application.name=team-sprint

# PostgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD:}

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=900000

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# SpringDoc
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
