spring.application.name=team-sprint

# App
app.base-url=${APP_BASE_URL:http://localhost:8080}

# PostgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD:}

# Email
spring.mail.host=smtp.gmail.com
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=900000

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# SpringDoc
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
