CREATE TABLE projects
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    title       VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    status      VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_projects PRIMARY KEY (id)
);

CREATE TABLE sprints
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    title       VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    status      VARCHAR(255)                            NOT NULL,
    start_date  TIMESTAMP WITHOUT TIME ZONE,
    due_date    TIMESTAMP WITHOUT TIME ZONE,
    project_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_sprints PRIMARY KEY (id)
);

CREATE TABLE tasks
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    title       VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    priority    VARCHAR(255),
    status      VARCHAR(255)                            NOT NULL,
    sprint_id   BIGINT                                  NOT NULL,
    assignee_id BIGINT,
    CONSTRAINT pk_tasks PRIMARY KEY (id)
);

CREATE TABLE user_projects
(
    project_id BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,
    CONSTRAINT pk_user_projects PRIMARY KEY (project_id, user_id)
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    username   VARCHAR(255)                            NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    role       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE sprints
    ADD CONSTRAINT FK_SPRINTS_ON_PROJECT FOREIGN KEY (project_id) REFERENCES projects (id);

ALTER TABLE tasks
    ADD CONSTRAINT FK_TASKS_ON_ASSIGNEE FOREIGN KEY (assignee_id) REFERENCES users (id);

ALTER TABLE tasks
    ADD CONSTRAINT FK_TASKS_ON_SPRINT FOREIGN KEY (sprint_id) REFERENCES sprints (id);

ALTER TABLE user_projects
    ADD CONSTRAINT fk_usepro_on_project FOREIGN KEY (project_id) REFERENCES projects (id);

ALTER TABLE user_projects
    ADD CONSTRAINT fk_usepro_on_user FOREIGN KEY (user_id) REFERENCES users (id);