ALTER TABLE verification_tokens
    DROP CONSTRAINT FK_VERIFICATION_TOKENS_ON_USER;

ALTER TABLE verification_tokens
    ADD CONSTRAINT FK_VERIFICATION_TOKENS_ON_USER
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON DELETE CASCADE;